site_name: Grid Mappers
site_url: 'https://gridmappers'
site_description: We aim to contribute to mapping countries' electricity grid systems around the world. We strive to improving the power infrastructure data on OpenStreetMap, to enhance global energy system modeling. 
repo_name: 'Grid-mappers'
repo_url: 'https://github.com/AndreasHD11/Grid-mappers'

nav:
  - The Initiative: index.md
  - Starter-kit tutorial: starter-kit.md
  - Tools: tools.md
  - Advanced kit: advanced-kit.md
  - Awesome List: awesome.md
  - Contribute & KPI: contributing.md
  - Validation checks:  validation-checks.md

copyright:    <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
      Creative Commons Attribution 4.0 International License   </a>

theme:
  name: material
  favicon: images/logo.png
  logo: images/logo.png
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light green
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light green
      accent: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.highlight
    - search.suggest
    - navigation.top

extra_css:
    - stylesheets/extra.css


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  
  